spring:
  profile.active: test
  datasource:
    url: jdbc:mysql://localhost/vollmed_api_test
    username: root
    password: 12345

## spring.datasource.url=jdbc:h2:mem:testdb
##spring.datasource.driverClassName=org.h2.Driver
## spring.datasource.username=sa
##spring.datasource.password=password
## spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

